url: "README.md" 


# Theme settings
theme: theme: jekyll-theme-leap-day
logo: "/assets/images/logo.png" # Add a logo in the "assets/images" folder


# Build settings
markdown: kramdown
highlighter: rouge

